---

hostname: "leaf-2"

host_side_ports:
    - te-1/1/3:
        vlan_mode: trunk
        vlans: [10,20,30,40]
    - te-1/1/4:
        vlan_mode: trunk
        vlans: [10,20,30,40]

network_side_ports:
    - te-1/1/1:
        routed-interface: "rif-p1"
    - te-1/1/2:
        routed-interface: "rif-p2"

loopback_interfaces:
    - lo:
        address: "4.4.4.4/32"

vrf_list:
    - vrf_name: "vrf1"
      vrf_address: "40.40.40.40/32"

host_side_vlan_interfaces:
    - vlan_interface: "vlan10"
      ipv4_address: "192.168.10.2/24"
      ipv6_address: "2001:0:0:1::2/64"
      router_mac: 00:00:10:00:00:FE
      vlan_id: 10
      vrf: "vrf1"
    - vlan_interface: "vlan20"
      ipv4_address: "192.168.20.2/24"
      ipv6_address: "2002:0:0:1::2/64"
      router_mac: 00:00:20:00:00:FE
      vlan_id: 20
      vrf: "vrf1"
    - vlan_interface: "vlan30"
      ipv4_address: "192.168.30.2/24"
      ipv6_address: "2003:0:0:1::2/64"
      router_mac: 00:00:30:00:00:FE
      vlan_id: 30
      vrf: "vrf1"
    - vlan_interface: "vlan40"
      ipv4_address: "192.168.40.2/24"
      ipv6_address: "2004:0:0:1::2/64"
      router_mac: 00:00:40:00:00:FE
      vlan_id: 40
      vrf: "vrf1"

network_side_vlan_interfaces:
    - vlan_interface: "vlan999"
      vlan_id: 999
      vrf: "vrf1"

vxlan_source_interface:
    interface: lo
    address: "4.4.4.4"

vxlan_vlan_mapping:
    - vni: 10010
      vlan: 10
      decapsulation: "service-vlan-per-port"
      arp-nd-suppress-disable: "false"
    - vni: 10020
      vlan: 20
      decapsulation: "service-vlan-per-port"
      arp-nd-suppress-disable: "false"
    - vni: 10030
      vlan: 30
      decapsulation: "service-vlan-per-port"
      arp-nd-suppress-disable: "false"
    - vni: 10040
      vlan: 40
      decapsulation: "service-vlan-per-port"
      arp-nd-suppress-disable: "false"

l3_vni:
    - vni: 4001
      vlan: 999
      vrf: "vrf1"

bgp:
    asn: 65020
    router-id: "4.4.4.4"
    peer-group: "underlay"
    interface:
        - "rif-p1"
        - "rif-p2"
    ipv4-unicast: "4.4.4.4/32"
    vrf:
        - vrf_name: "vrf1"
          ipv4-unicast: "40.40.40.40/32"
