---

hostname: "spine-1"

network_side_ports:
    - te-1/1/1:
        routed-interface: "rif-p1"
    - te-1/1/2:
        routed-interface: "rif-p2"
    - te-1/1/3:
        routed-interface: "rif-p3"
    - te-1/1/4:
        routed-interface: "rif-p4"

loopback_interfaces:
    - lo:
        address: "1.1.1.1/32"

bgp:
    asn: 65199
    router-id: "1.1.1.1"
    peer-group: "underlay"
    interface:
        - "rif-p1"
        - "rif-p2"
        - "rif-p3"
        - "rif-p4"
    ipv4-unicast: "1.1.1.1/32"
